name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          token: ${{ secrets.GH_PAT }}
          card: stats
          fail_on_error: true
          options: "username=Mukilan-s18&show_icons=true&theme=tokyonight&hide_border=true&include_all_commits=true&count_private=true&bg_color=0d1117&title_color=70a5fd&icon_color=bf91f3&text_color=c9d1d9&border_radius=10"
          path: github-metrics/stats.svg

      - name: Generate GitHub Top Langs Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          token: ${{ secrets.GH_PAT }}
          card: top-langs
          fail_on_error: true
          options: "username=Mukilan-s18&layout=compact&theme=tokyonight&hide_border=true&count_private=true&bg_color=0d1117&title_color=70a5fd&text_color=c9d1d9&langs_count=8&border_radius=10"
          path: github-metrics/top-langs.svg

      - name: Commit and push generated cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-metrics/*.svg
          git commit -m "Update GitHub stats cards" || exit 0
          git push
